env:
    global:
        - CC_TEST_REPORTER_ID=fbdd0a19b4dc2e747c732dd3db87d7823c63f2d1503e95660788e06a0c2fc862
language: python
python: 3.7
install:
    - pip install projects/project1/requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
