[cosmic-ray]
module-path = "./src/fysstatistics.py"
python-version = ""
timeout = 10.0
excluded-modules = ["src/resources.py", "src/turbo.py", "test*", "turbo*", "turbo.py"]
test-command = "pytest tests"

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = []
